# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('time2eat', '0002_auto_20160813_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayOfWeek', models.CharField(max_length=1)),
                ('Start', models.CharField(max_length=8)),
                ('CloseMid', models.CharField(default='', max_length=8)),
                ('StartMid', models.CharField(default='', max_length=8)),
                ('Close', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DishName', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('isSpicy', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField()),
                ('date', models.CharField(max_length=10)),
                ('period', models.CharField(max_length=3)),
                ('total', models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNum', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SmallOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=5)),
                ('dish', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='time2eat.Dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time2eat.Order')),
                ('orderUser', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='resprof',
            old_name='restaurant',
            new_name='ResName',
        ),
        migrations.RemoveField(
            model_name='resprof',
            name='create',
        ),
        migrations.RemoveField(
            model_name='resprof',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='resprof',
            name='service_h',
        ),
        migrations.RemoveField(
            model_name='type',
            name='country',
        ),
        migrations.AddField(
            model_name='resprof',
            name='country',
            field=models.CharField(default='taiwan', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time2eat.ResProf'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time2eat.ResProf'),
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time2eat.ResProf'),
        ),
        migrations.AddField(
            model_name='date',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time2eat.ResProf'),
        ),
    ]
