# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 07:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('time2eat', '0003_auto_20160918_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='EatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UpperUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavorDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.DecimalField(decimal_places=0, max_digits=4)),
                ('EatUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time2eat.EatUser')),
            ],
        ),
        migrations.CreateModel(
            name='FavorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.DecimalField(decimal_places=0, max_digits=4)),
                ('EatUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time2eat.EatUser')),
            ],
        ),
        migrations.CreateModel(
            name='ResFavorDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.DecimalField(decimal_places=0, max_digits=6)),
                ('dateOfMon_Year', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='resprof',
            name='district',
        ),
        migrations.AlterField(
            model_name='smallorder',
            name='orderUser',
            field=models.ManyToManyField(to='time2eat.EatUser'),
        ),
        migrations.AddField(
            model_name='resfavordish',
            name='Res',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time2eat.ResProf'),
        ),
        migrations.AddField(
            model_name='resfavordish',
            name='dish',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='time2eat.Dish'),
        ),
    ]
