# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time2eat', '0004_auto_20160928_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=0, max_digits=5)),
                ('date', models.CharField(max_length=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time2eat.Order')),
                ('orderUser', models.ManyToManyField(to='time2eat.EatUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='smallorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='smallorder',
            name='orderUser',
        ),
        migrations.AlterField(
            model_name='smallorder',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='smallorder',
            name='UserOrder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='time2eat.UserOrder'),
            preserve_default=False,
        ),
    ]
