# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time2eat', '0005_auto_20161002_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='date',
        ),
        migrations.AddField(
            model_name='eatuser',
            name='FDish',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='time2eat.Dish'),
        ),
        migrations.AddField(
            model_name='eatuser',
            name='FType',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='time2eat.Type'),
        ),
        migrations.AddField(
            model_name='favordish',
            name='dish',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='time2eat.Dish'),
        ),
        migrations.AddField(
            model_name='favortype',
            name='type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='time2eat.Type'),
        ),
        migrations.AddField(
            model_name='userorder',
            name='create',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='CloseMid',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='StartMid',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='DishName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resfavordish',
            name='dish',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='time2eat.Dish'),
        ),
        migrations.AlterField(
            model_name='resprof',
            name='ResName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='resprof',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='ResType',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
