# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time2eat', '0006_auto_20161002_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='orderUser',
        ),
        migrations.AddField(
            model_name='userorder',
            name='orderUser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='time2eat.EatUser'),
        ),
    ]
