# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time2eat', '0007_auto_20161002_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatuser',
            name='FDish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='time2eat.Dish'),
        ),
        migrations.AlterField(
            model_name='eatuser',
            name='FType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='time2eat.Type'),
        ),
    ]
