# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time2eat', '0008_auto_20161003_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favordish',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='time2eat.Dish'),
        ),
        migrations.AlterField(
            model_name='favortype',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='time2eat.Type'),
        ),
        migrations.AlterField(
            model_name='resfavordish',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='time2eat.Dish'),
        ),
        migrations.AlterField(
            model_name='smallorder',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time2eat.Dish'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='orderUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='time2eat.EatUser'),
        ),
    ]
