# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-09 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time2eat', '0009_auto_20161003_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='resprof',
            name='avatar',
            field=models.ImageField(default='images/time2eat/restaurant.svg', upload_to=''),
        ),
    ]
