# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time2eat', '0010_auto_20161009_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='images/time2eat/turkey.svg', upload_to=''),
        ),
        migrations.AddField(
            model_name='resprof',
            name='envText',
            field=models.CharField(default='以新鮮食材佐特製湯頭，搭配風格設計空間，讓聚餐除了享受美食，也能提升時尚品味！', max_length=255),
        ),
        migrations.AddField(
            model_name='resprof',
            name='environment',
            field=models.ImageField(default='images/time2eat/burger.svg', upload_to=''),
        ),
        migrations.AddField(
            model_name='resprof',
            name='feature',
            field=models.ImageField(default='images/time2eat/noodles.svg', upload_to=''),
        ),
        migrations.AddField(
            model_name='resprof',
            name='featureText',
            field=models.CharField(default='均勻分布的油花與鮮紅肉質，讓口感更加紮實不凡，肉獨有的香氣與油花潤飾，放進精心熬煮清甜的湯汁中輕涮，令人流連忘返的香滑柔嫩口感，讓你感動不已！', max_length=255),
        ),
    ]
