# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoDemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='path',
            field=models.CharField(default='', max_length=400),
        ),
    ]
