# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoDemo', '0002_auto_20170703_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
