# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-04 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infernoWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='admin', max_length=7),
            preserve_default=False,
        ),
    ]
