# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-05 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infernoWeb', '0002_user_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('name', 'facebookid')]),
        ),
    ]
